easy_admin:
  design:
    menu:
      - {label: "Entities"}
      - label: "Posts"
        children:
          - {entity: Post, label: "Posts list", icon: "th-list"}
          - {entity: Post, label: "Add post", icon: "plus", params: {action: 'new'}}
      - label: "Category"
        children:
          - {entity: Category, label: "List all categories", icon: "th-list"}
          - {entity: Category, label: "Add category", icon: "plus"}
      - Tag
      - {label: "Settings"}
      - {entity: User, icon: "user"}
  site_name: 'Luca <b style="color:DodgerBlue;">Dowden</b>'
  user:
    display_name: true
    display_avatar: true
    name_property_path: 'fullName'
  entities:
    Post:
      class: App\Entity\Post
      label: "Post"
      form:
        fields:
            - {type: 'group', icon: 'pencil', label: 'Basic Information', css_class: 'col-lg-7'}
            - title
            - {property: 'content', type: 'text_editor'}
            - createdAt
            - published
            - {type: 'group', icon: 'th-list', label: 'Other Information', css_class: 'col-lg-5'}
            - category
            - tags
            - {type: 'group', icon: 'clip', label: 'Attachments', css_class: 'col-lg-5'}
            - { property: 'thumbnailFile', type: 'vich_image' }
      list:
        collapse_actions: true
        actions: ['show', 'edit', 'delete']
        batch_actions: ['delete']
        title: "Some posts from the other world"
        fields: ['title', 'content', 'createdAt', {property: 'thumbnail', type: 'image', base_path: '%uploads_path%'}]
        filters: ['published']
      show:
        fields:
          - title
          - {property: 'content', type: 'raw'}
          - createdAt
          - published
          - {property: 'thumbnail', type: 'image', base_path: '%uploads_path%'}
      edit:
        help: "Hello there"
        fields:
          - '-tags'


    Category:
      class: App\Entity\Category
    Tag:
      class: App\Entity\Tag
      form:
        fields:
          - name
          - slug
    User:
      class: App\Entity\User